### ISSUE TITLE
How to run code in constructor only if current page matches the controller ?

### ISSUE THREAD

**Issue by ligne13** [soberwp/controller#118]
I would like to run some code I've put in my constructor but only if the current page uses the Controller. I've tried to use get_the_ID() to check the current page ID but it returns false.

By the way, I find strange that every Controller constructor is run whatever the page/post/template is displayed. I think the purpose of Controllers based on WP hierarchy is to run only if the Controller matches the current page/post being displayed.

How can I do that ?

Here's my code :

```
class TemplateCustom extends Controller {
    public function __construct() {
        var_dump(get_the_ID()); // false
        if ( get_the_ID() === 508 ) { // the ID of my page
            // run some code here...
        }
    }
}
```

thanks.

**Comment by codepuncher** [comment]
Have you tried using the `__before` or `__after` methods instead? They are used at different points of the controller execution ([see here](https://github.com/soberwp/controller/blob/76a4181e2ceb47232cb5fe0062512ce97b543bf5/controller.php#L66)).
Also, you can create a Controller for specific pages/posts by creating a controller named `Page508` instead of something like `TemplateCustom`. Anything in the page body class that is affixed with `-data` can be used in this way.
It may be worth then putting your code you want to run into a trait/partial to include in multiple Controllers.

**Comment by ligne13** [comment]
Hi @codepuncher ,

I finally used the hook `the_post` inside the __construct method, so I can access the post ID.

```
public function __construct() {
    add_action( 'the_post', function () {
        if ( get_the_ID() === XXX ) {
            // ...
        }
}
```

thanks !
