### ISSUE TITLE
traits

### ISSUE THREAD

**Issue by jajouka79** [soberwp/controller#13]
ive got a trait that require data set in another trait, when i try to use trait 1 inside trait2, i get an not found error. is it possible to do this?

**Comment by darrenjacoby** [comment]
@jajouka79 have you tried creating a function within trait1 to return the data? (getter function).  

Otherwise, the issue may be that the file for trait2 is being included before trait1, you could try rename trait1 to be alphabetically before trait2.  I know that's not ideal, but let me know if that works and I'll see if I can implement some kind of include override option.

**Comment by darrenjacoby** [comment]
I have given this thought, and feel best practice would be to not require traits within traits.  It's going to become a mess quick.  I would recommend creating traits that return values in a way that you can use them within the Controller together.

**Comment by monstertuning** [comment]
yes, i've come to this conclusion also. making traits dynamic with external methods will work ok for now, thanks
