### ISSUE TITLE
Adding actions and filters

### ISSUE THREAD

**Issue by thomascharbit** [soberwp/controller#19]
Hi,

I was wondering if Controller could be used to also run actions and filters for specific templates?

For example on an archive template I might need to change default query with pre_get_posts, change excerpt length, etc.

Using the hierarchy to run them makes sense, so can we use Controller for this?

Thanks!

**Comment by darrenjacoby** [comment]
Hi @thomascharbit,

At the moment that is not possible.  

You could however place the filters in src/ and use conditional tags to target specific templates. You could also use a custom public static function to alter a loop or excerpt length and call that instead of using a filter.  I would encourage this method if possible.

However, I will see if I can work into the scope of Controller.

**Comment by thomascharbit** [comment]
Hi Darren,

Thanks for your answer, i understand the solutions you proposed but i still think there is room for improvement :) Hope to see this implemented maybe someday!

**Comment by darrenjacoby** [comment]
I'm going to close for now, but will give this some work/thought to see how it could be implemented within the Controller.
