### ISSUE TITLE
Do not force project namespace

### ISSUE THREAD

**Issue by schrapel** [soberwp/controller#53]
We should not be forced to use the `App/Controller` namespace and be able to change `App` to our projects namespace.

Thanks.

**Comment by darrenjacoby** [comment]
@schrapel dev-master uses PSR4 autoloading, so you should be able to specify?

**Comment by schrapel** [comment]
@darrenjacoby you specifically require it https://github.com/soberwp/controller/blob/master/src/Loader.php#L110

**Comment by darrenjacoby** [comment]
That is a good point. I may need to add a filter for that.

**Comment by schrapel** [comment]
You could read the namespace in the file.

**Comment by webstractions** [comment]
Laravel uses a config file to declare where the User model class is. By default, it is in the app root. Devs can relocate models into their own folder and edit the location easily.

There are paths being declared in `config\theme.php` already. Adding a controller path is simple enough.

**Comment by darrenjacoby** [comment]
@schrapel @webstractions 

Looking into this, for Loader, I need to know the path of the Controllers to get the filelist to run through. There is a filter for that currently. PSR4 uses folder structure, so that could be used to determine the namespace as well. I may switch it around, so the user can enter the custom namespace and from there I can find the path for the filelist in the background.
