### ISSUE TITLE
Template controllers not loaded in 'draft' mode

### ISSUE THREAD

**Issue by abstrakt** [soberwp/controller#70]
It seems that the correct controllers are not being loaded when previewing a page in draft mode. However, Sage 9 does successfully load the correct view.

It loads all the basic controllers:

- controllers/app.php
- controllers/index.php
- controllers/singular.php
- controllers/page.php

But unfortunately not the template that is assigned to it.

**Comment by darrenjacoby** [comment]
I will test and look at fixing in 2.0.2

**Comment by darrenjacoby** [comment]
This is working with 2.0.1 from my testing. I'd recommend upgrading and trying again. https://github.com/roots/sage/pull/2025

**Comment by darrenjacoby** [comment]
Haha, ok, this is working with 2.0.1.

**Comment by slackday** [comment]
Hi @darrenjacoby can you test this again? I'm having the same problem and I have tried updating to 2.1.0.

When assigning a custom page template the normal Page controller is loaded. And I don't use `$tree = true` on the custom template controller.

**Comment by darrenjacoby** [comment]
@slackday I'm pretty busy for the next month but will take a look when I have a chance.

**Comment by slackday** [comment]
I had some time today to tackle this problem again. Turns out it was not an issue with the Controller itself but rather an upstream error in `brain/hierarchy` which the Controller uses. 

When a page with a custom template is in preview (before it is saved first time) it does not have a `page_name`. The hierarchy would return standard Page/Singular hierarchy.

I suspect the reason this would work for some people and not for others is the difference if the page would be previewed first time or after it had been published. 

I have [created a PR](https://github.com/Brain-WP/Hierarchy/pull/16) which solves this issue. I hope it can be merged soon or if the maintainer comes up with a better solution. I don't know the inner works of Hierarchy nor the Controller so this was quite dive 😄.

**Comment by darrenjacoby** [comment]
Thanks for investigating @slackday , it looks like progress is being made over at brain/hierarchy. I will close this for now, and update the version of brain/hierarchy on dev-master soon.
